/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlgPrintBattleforce.java
 *
 * Created on Sep 12, 2009, 2:46:04 PM
 */

package ssw.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import ssw.battleforce.BattleForce;

/**
 *
 * @author gblouin
 */
public class dlgPrintBattleforce extends javax.swing.JDialog {
    private BattleForce force;
    public boolean Result = false;
    public String Sheet = BattleForce.InnerSphere;

    /** Creates new form dlgPrintBattleforce */
    public dlgPrintBattleforce(java.awt.Frame parent, boolean modal, BattleForce force) {
        super(parent, modal);
        initComponents();

        this.force = force;
        lblForceSize.setText(force.BattleForceStats.size()+"");

        btnIS.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Sheet = BattleForce.InnerSphere;
            }
        });

        btnCL.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Sheet = BattleForce.Clan;
            }
        });

        btnCS.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                Sheet = BattleForce.Comstar;
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpUnitSize = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnIS = new javax.swing.JRadioButton();
        btnCS = new javax.swing.JRadioButton();
        btnCL = new javax.swing.JRadioButton();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblForceSize = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BattleForce Print Options");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sheet Type"));

        btnGrpUnitSize.add(btnIS);
        btnIS.setText("Inner Sphere Lance (4)");

        btnGrpUnitSize.add(btnCS);
        btnCS.setText("Comstar/Word of Blake Level II (6)");

        btnGrpUnitSize.add(btnCL);
        btnCL.setText("Clan Star (5)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCS)
                    .addComponent(btnCL)
                    .addComponent(btnIS))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnIS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCS))
        );

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        jLabel1.setText("Selected Force:");

        lblForceSize.setText("12");

        jLabel3.setText("units");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(99, Short.MAX_VALUE)
                .addComponent(btnPrint)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblForceSize)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblForceSize)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint)
                    .addComponent(btnCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Result = true;
        setVisible(false);
    }//GEN-LAST:event_btnPrintActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnCL;
    private javax.swing.JRadioButton btnCS;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrpUnitSize;
    private javax.swing.JRadioButton btnIS;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblForceSize;
    // End of variables declaration//GEN-END:variables

}
