/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dlgPrintSavedMechOptions.java
 *
 * Created on Jan 14, 2009, 6:37:10 PM
 * * @author Michael Mills
 */

package ssw.gui;

import ssw.CommonTools;
import ssw.components.Mech;
import java.util.Vector;
import ssw.components.ifLoadout;
import ssw.print.PrintMech;


public class dlgPrintSavedMechOptions extends javax.swing.JDialog {
    private Mech CurMech;
    private frmMain Parent;
    private boolean Result = false;

    /** Creates new form dlgPrintSavedMechOptions */
    public dlgPrintSavedMechOptions(java.awt.Frame parent, boolean modal, Mech m, String Warrior, int Gunnery, int Piloting) {
        super(parent, modal);
        initComponents();
        Parent = (frmMain) parent;
        CurMech = m;
        txtWarriorName.setText( Warrior );
        cmbGunnery.setSelectedIndex( Gunnery );
        cmbPiloting.setSelectedIndex( Piloting );
        txtMechName.setText(CurMech.GetFullName());
        if( CurMech.IsOmnimech()){
            Vector Loadouts = CurMech.GetLoadouts();
            ifLoadout tempLoadout;
            cmbOmniVariant.setMaximumRowCount(Loadouts.size()+1);
            for (int i = 0; i < Loadouts.size();  ++i){
                tempLoadout = (ifLoadout) Loadouts.get(i);
                cmbOmniVariant.addItem(tempLoadout.GetName());
                if (CurMech.GetLoadout().GetName().equals(tempLoadout.GetName())) {cmbOmniVariant.setSelectedItem(tempLoadout.GetName());}
                //CurMech.SetCurLoadout((String) cmbOmniVariant.getSelectedItem());
            }
            cmbOmniVariant.removeItem("Not an Omni-Mech");
        }
        else{
            cmbOmniVariant.setEnabled(false);
        }
        lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
        chkPrintCharts.setSelected(Parent.Prefs.getBoolean("UseCharts", false));
        chkAdjustBV.setSelected(Parent.Prefs.getBoolean("AdjustPG", false));
        chkMWStats.setSelected(Parent.Prefs.getBoolean("NoPilot", false));
        if (Parent.Prefs.getBoolean("UseA4", false)) {
            cmbPaperSize.setSelectedIndex(1);
        }

    }

    public dlgPrintSavedMechOptions(java.awt.Frame parent, boolean modal, Mech m) {
        this(parent, modal, m, "", 4, 5);
    }

    public dlgPrintSavedMechOptions(java.awt.Frame parent, boolean modal, PrintMech m) {
        this(parent, modal, m.CurMech, m.getMechwarrior(), m.getGunnery(), m.getPiloting());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        txtWarriorName = new javax.swing.JTextField();
        chkAdjustBV = new javax.swing.JCheckBox();
        chkPrintCharts = new javax.swing.JCheckBox();
        lblAdjustBVLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnPrint = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        cmbGunnery = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbPiloting = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        lblAdjustBV = new javax.swing.JLabel();
        chkMWStats = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbPaperSize = new javax.swing.JComboBox();
        cmbOmniVariant = new javax.swing.JComboBox();
        txtMechName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Print Saved Mech");

        txtWarriorName.setMaximumSize(new java.awt.Dimension(150, 20));
        txtWarriorName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtWarriorName.setPreferredSize(new java.awt.Dimension(150, 20));

        chkAdjustBV.setText("Adjust BV for Gunnery/Piloting");
        chkAdjustBV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAdjustBVActionPerformed(evt);
            }
        });

        chkPrintCharts.setText("Print helpful charts on the sheet");

        lblAdjustBVLabel.setText("Adjusted BV:");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrint);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        cmbGunnery.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbGunnery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGunneryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(cmbGunnery, gridBagConstraints);

        jLabel1.setText("Gunnery");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Piloting");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel2.add(jLabel2, gridBagConstraints);

        cmbPiloting.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));
        cmbPiloting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilotingActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 0, 0);
        jPanel2.add(cmbPiloting, gridBagConstraints);

        jLabel3.setText("MechWarrior Name");

        lblAdjustBV.setText("00,000");

        chkMWStats.setText("Do not print MechWarrior stats");
        chkMWStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkMWStatsActionPerformed(evt);
            }
        });

        jLabel5.setText("Paper Size:");
        jPanel3.add(jLabel5);

        cmbPaperSize.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Letter", "A4" }));
        jPanel3.add(cmbPaperSize);

        cmbOmniVariant.setMaximumRowCount(1);
        cmbOmniVariant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not an Omni-Mech" }));
        cmbOmniVariant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOmniVariantActionPerformed(evt);
            }
        });

        txtMechName.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMechName, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtWarriorName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkMWStats))
                        .addGap(4, 4, 4)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkAdjustBV)
                        .addGap(22, 22, 22)
                        .addComponent(lblAdjustBVLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkPrintCharts)
                        .addGap(26, 26, 26)
                        .addComponent(lblAdjustBV))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbOmniVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtMechName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbOmniVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtWarriorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chkMWStats))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAdjustBV)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblAdjustBVLabel)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkPrintCharts)
                    .addComponent(lblAdjustBV))
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAdjustBVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAdjustBVActionPerformed
        if( chkAdjustBV.isSelected() ) {
            lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
        } else {
            lblAdjustBV.setText( String.format( "%1$,d", CurMech.GetCurrentBV() ) );
        }
}//GEN-LAST:event_chkAdjustBVActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        Parent.Prefs.putBoolean("UseA4", UseA4Paper());
        Parent.Prefs.putBoolean("UseCharts", chkPrintCharts.isSelected());
        Parent.Prefs.putBoolean("AdjustPG", chkAdjustBV.isSelected());
        Parent.Prefs.putBoolean("NoPilot", chkMWStats.isSelected());

        Result = true;
        setVisible( false );
}//GEN-LAST:event_btnPrintActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        setVisible( false );
}//GEN-LAST:event_btnCancelActionPerformed

    private void cmbGunneryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGunneryActionPerformed
        if( chkAdjustBV.isSelected() ) {
            lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
        }
}//GEN-LAST:event_cmbGunneryActionPerformed

    private void cmbPilotingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilotingActionPerformed
        if( chkAdjustBV.isSelected() ) {
            lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
        }
}//GEN-LAST:event_cmbPilotingActionPerformed

    private void chkMWStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkMWStatsActionPerformed
        if( chkMWStats.isSelected() ) {
            lblAdjustBV.setText( String.format( "%1$,d", CurMech.GetCurrentBV() ) );
            chkAdjustBV.setSelected( false );
            chkAdjustBV.setEnabled( false );
            cmbGunnery.setEnabled( false );
            cmbPiloting.setEnabled( false );
            txtWarriorName.setEnabled( false );
        } else {
            lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
            cmbGunnery.setEnabled( true );
            cmbPiloting.setEnabled( true );
            txtWarriorName.setEnabled( true );
            chkAdjustBV.setEnabled( true );
        }
}//GEN-LAST:event_chkMWStatsActionPerformed

    private void cmbOmniVariantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOmniVariantActionPerformed
        // TODO add your handling code here:
        CurMech.SetCurLoadout((String) cmbOmniVariant.getSelectedItem());
        lblAdjustBV.setText( String.format( "%1$,.0f", CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() ) ) );
    }//GEN-LAST:event_cmbOmniVariantActionPerformed

    public boolean Result() {
        return Result;
    }

    public boolean PrintPilot() {
        return ! chkMWStats.isSelected();
    }

    public String GetWarriorName() {
        return txtWarriorName.getText();
    }

    public int GetGunnery() {
        return cmbGunnery.getSelectedIndex();
    }

    public int GetPiloting() {
        return cmbPiloting.getSelectedIndex();
    }

    public boolean AdjustBV() {
        return chkAdjustBV.isSelected();
    }

    public float GetAdjustedBV() {
        return CommonTools.GetAdjustedBV( CurMech.GetCurrentBV(), cmbGunnery.getSelectedIndex(), cmbPiloting.getSelectedIndex() );
    }

    public boolean PrintCharts() {
        return chkPrintCharts.isSelected();
    }

    public boolean UseA4Paper() {
        if( cmbPaperSize.getSelectedIndex() == 0 ) {
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JCheckBox chkAdjustBV;
    private javax.swing.JCheckBox chkMWStats;
    private javax.swing.JCheckBox chkPrintCharts;
    private javax.swing.JComboBox cmbGunnery;
    private javax.swing.JComboBox cmbOmniVariant;
    private javax.swing.JComboBox cmbPaperSize;
    private javax.swing.JComboBox cmbPiloting;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAdjustBV;
    private javax.swing.JLabel lblAdjustBVLabel;
    private javax.swing.JTextField txtMechName;
    private javax.swing.JTextField txtWarriorName;
    // End of variables declaration//GEN-END:variables

}
