/*
Copyright (c) 2010, Justin R. Bengtson (poopshotgun@yahoo.com)
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
        this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
        this list of conditions and the following disclaimer in the
        documentation and/or other materials provided with the distribution.
    * Neither the name of Justin R. Bengtson nor the names of contributors may
        be used to endorse or promote products derived from this software
        without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

package ssw.gui;

import javax.swing.Box;

public class frmCompat extends javax.swing.JFrame {

    /** Creates new form frmCompat */
    public frmCompat() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tlbIconBar = new javax.swing.JToolBar();
        btnNewIcon = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSaveIcon = new javax.swing.JButton();
        btnPrintPreview = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnPrintIcon = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnExportClipboardIcon = new javax.swing.JButton();
        btnExportHTMLIcon = new javax.swing.JButton();
        btnExportTextIcon = new javax.swing.JButton();
        btnExportMTFIcon = new javax.swing.JButton();
        btnChatInfo = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        btnPostToS7 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        btnAddToForceList = new javax.swing.JButton();
        btnForceList = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JToolBar.Separator();
        btnOptionsIcon = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JToolBar.Separator();
        lblSelectVariant = new javax.swing.JLabel();
        cmbOmniVariant = new javax.swing.JComboBox();
        tbpMainTabPane = new javax.swing.JTabbedPane();
        pnlBasicSetup = new javax.swing.JPanel();
        pnlBasicSetupLeft = new javax.swing.JPanel();
        pnlBasicInformation = new javax.swing.JPanel();
        pnlBasicInfo1 = new javax.swing.JPanel();
        lblMechName = new javax.swing.JLabel();
        txtMechName = new javax.swing.JTextField();
        pnlBasicInfo2 = new javax.swing.JPanel();
        lblModel = new javax.swing.JLabel();
        txtMechModel = new javax.swing.JTextField();
        pnlBasicInfo3 = new javax.swing.JPanel();
        lblMechSource = new javax.swing.JLabel();
        txtSource = new javax.swing.JTextField();
        pnlBasicInfo4 = new javax.swing.JPanel();
        lblRulesLevel = new javax.swing.JLabel();
        cmbRulesLevel = new javax.swing.JComboBox();
        pnlBasicInfo5 = new javax.swing.JPanel();
        lblMechEra = new javax.swing.JLabel();
        cmbMechEra = new javax.swing.JComboBox();
        pnlBasicInfo6 = new javax.swing.JPanel();
        lblTechBase = new javax.swing.JLabel();
        cmbTechBase = new javax.swing.JComboBox();
        pnlBasicInfo7 = new javax.swing.JPanel();
        lblEraYears = new javax.swing.JLabel();
        pnlBasicInfo8 = new javax.swing.JPanel();
        lblProdYear = new javax.swing.JLabel();
        txtProdYear = new javax.swing.JTextField();
        pnlBasicInfo9 = new javax.swing.JPanel();
        chkYearRestrict = new javax.swing.JCheckBox();
        pnlBasicInfo10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        cmbFluffEra = new javax.swing.JComboBox();
        pnlChassis = new javax.swing.JPanel();
        pnlChassis1 = new javax.swing.JPanel();
        lblTonnage = new javax.swing.JLabel();
        cmbTonnage = new javax.swing.JComboBox();
        lblMechType = new javax.swing.JLabel();
        pnlChassis2 = new javax.swing.JPanel();
        lblUnitType = new javax.swing.JLabel();
        cmbMechType = new javax.swing.JComboBox();
        pnlChassis3 = new javax.swing.JPanel();
        lblMotiveType = new javax.swing.JLabel();
        cmbMotiveType = new javax.swing.JComboBox();
        pnlChassis4 = new javax.swing.JPanel();
        chkOmnimech = new javax.swing.JCheckBox();
        pnlChassis5 = new javax.swing.JPanel();
        lblInternalType = new javax.swing.JLabel();
        cmbInternalType = new javax.swing.JComboBox();
        pnlChassis6 = new javax.swing.JPanel();
        lblEngineType = new javax.swing.JLabel();
        cmbEngineType = new javax.swing.JComboBox();
        pnlChassis7 = new javax.swing.JPanel();
        lblGyroType = new javax.swing.JLabel();
        cmbGyroType = new javax.swing.JComboBox();
        pnlChassis8 = new javax.swing.JPanel();
        lblCockpit = new javax.swing.JLabel();
        cmbCockpitType = new javax.swing.JComboBox();
        pnlChassis9 = new javax.swing.JPanel();
        chkCommandConsole = new javax.swing.JCheckBox();
        pnlChassis10 = new javax.swing.JPanel();
        lblPhysEnhance = new javax.swing.JLabel();
        cmbPhysEnhance = new javax.swing.JComboBox();
        pnlBasicSetupCenter = new javax.swing.JPanel();
        pnlBasicSetupRight = new javax.swing.JPanel();
        pnlArmor = new javax.swing.JPanel();
        pnlEquipment = new javax.swing.JPanel();
        pnlCriticals = new javax.swing.JPanel();
        pnlFluff = new javax.swing.JPanel();
        pnlCharts = new javax.swing.JPanel();
        pnlBattleforce = new javax.swing.JPanel();
        pnlInfoPanel = new javax.swing.JPanel();
        txtInfoTonnage = new javax.swing.JTextField();
        txtInfoFreeTons = new javax.swing.JTextField();
        txtInfoMaxHeat = new javax.swing.JTextField();
        txtInfoHeatDiss = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtInfoUnplaced = new javax.swing.JTextField();
        txtInfoBattleValue = new javax.swing.JTextField();
        txtInfoCost = new javax.swing.JTextField();
        mnuMainMenu = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuNewMech = new javax.swing.JMenuItem();
        mnuLoad = new javax.swing.JMenuItem();
        mnuOpen = new javax.swing.JMenuItem();
        mnuImport = new javax.swing.JMenu();
        mnuImportHMP = new javax.swing.JMenuItem();
        mnuBatchHMP = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JSeparator();
        mnuSave = new javax.swing.JMenuItem();
        mnuSaveAs = new javax.swing.JMenuItem();
        mnuExport = new javax.swing.JMenu();
        mnuExportHTML = new javax.swing.JMenuItem();
        mnuExportMTF = new javax.swing.JMenuItem();
        mnuExportTXT = new javax.swing.JMenuItem();
        mnuExportClipboard = new javax.swing.JMenuItem();
        mnuCreateTCGMech = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JSeparator();
        mnuPrint = new javax.swing.JMenu();
        mnuPrintCurrentMech = new javax.swing.JMenuItem();
        mnuPrintSavedMech = new javax.swing.JMenuItem();
        mnuPrintBatch = new javax.swing.JMenuItem();
        mnuPrintPreview = new javax.swing.JMenuItem();
        mnuPostS7 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JSeparator();
        mnuExit = new javax.swing.JMenuItem();
        mnuTools = new javax.swing.JMenu();
        mnuSummary = new javax.swing.JMenuItem();
        mnuCostBVBreakdown = new javax.swing.JMenuItem();
        mnuTextTRO = new javax.swing.JMenuItem();
        mnuUnlock = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JSeparator();
        mnuOptions = new javax.swing.JMenuItem();
        mnuViewToolbar = new javax.swing.JCheckBoxMenuItem();
        mnuClearUserData = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuCredits = new javax.swing.JMenuItem();
        mnuAboutSSW = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        tlbIconBar.setFloatable(false);
        tlbIconBar.setRollover(true);
        tlbIconBar.setFocusable(false);
        tlbIconBar.setPreferredSize(new java.awt.Dimension(30, 30));
        tlbIconBar.setRequestFocusEnabled(false);
        tlbIconBar.setVerifyInputWhenFocusTarget(false);

        btnNewIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/document--plus.png"))); // NOI18N
        btnNewIcon.setToolTipText("Create New 'Mech");
        btnNewIcon.setFocusable(false);
        btnNewIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnNewIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnNewIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnNewIcon);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/folder-open-document.png"))); // NOI18N
        btnOpen.setToolTipText("Open Dialogue");
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setMinimumSize(new java.awt.Dimension(28, 28));
        btnOpen.setPreferredSize(new java.awt.Dimension(28, 28));
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnOpen);

        btnSaveIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/disk-black.png"))); // NOI18N
        btnSaveIcon.setToolTipText("Save Current 'Mech");
        btnSaveIcon.setFocusable(false);
        btnSaveIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaveIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnSaveIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnSaveIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnSaveIcon);

        btnPrintPreview.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/projection-screen.png"))); // NOI18N
        btnPrintPreview.setToolTipText("Print Preview");
        btnPrintPreview.setFocusable(false);
        btnPrintPreview.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrintPreview.setMinimumSize(new java.awt.Dimension(28, 28));
        btnPrintPreview.setPreferredSize(new java.awt.Dimension(28, 28));
        btnPrintPreview.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnPrintPreview);
        tlbIconBar.add(jSeparator1);

        btnPrintIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/printer.png"))); // NOI18N
        btnPrintIcon.setToolTipText("Print This 'Mech");
        btnPrintIcon.setFocusable(false);
        btnPrintIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrintIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnPrintIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnPrintIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnPrintIcon);
        tlbIconBar.add(jSeparator2);

        btnExportClipboardIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/document-clipboard.png"))); // NOI18N
        btnExportClipboardIcon.setToolTipText("Export 'Mech to Clipboard in TRO Format");
        btnExportClipboardIcon.setFocusable(false);
        btnExportClipboardIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportClipboardIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnExportClipboardIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnExportClipboardIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnExportClipboardIcon);

        btnExportHTMLIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/document-image.png"))); // NOI18N
        btnExportHTMLIcon.setToolTipText("Export 'Mech to HTML");
        btnExportHTMLIcon.setFocusable(false);
        btnExportHTMLIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportHTMLIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnExportHTMLIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnExportHTMLIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnExportHTMLIcon);

        btnExportTextIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/document-text.png"))); // NOI18N
        btnExportTextIcon.setToolTipText("Export 'Mech to Text/TRO File");
        btnExportTextIcon.setFocusable(false);
        btnExportTextIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportTextIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnExportTextIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnExportTextIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnExportTextIcon);

        btnExportMTFIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/document--arrow.png"))); // NOI18N
        btnExportMTFIcon.setToolTipText("Export 'Mech to MTF (MegaMek) Format");
        btnExportMTFIcon.setFocusable(false);
        btnExportMTFIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExportMTFIcon.setMinimumSize(new java.awt.Dimension(28, 28));
        btnExportMTFIcon.setPreferredSize(new java.awt.Dimension(28, 28));
        btnExportMTFIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnExportMTFIcon);

        btnChatInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/balloon.png"))); // NOI18N
        btnChatInfo.setToolTipText("Export 'Mech to Clipboard in Chat Format (Brief Info)");
        btnChatInfo.setFocusable(false);
        btnChatInfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnChatInfo.setMinimumSize(new java.awt.Dimension(28, 28));
        btnChatInfo.setPreferredSize(new java.awt.Dimension(28, 28));
        btnChatInfo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnChatInfo);
        tlbIconBar.add(jSeparator3);

        btnPostToS7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/server.png"))); // NOI18N
        btnPostToS7.setToolTipText("Post 'Mech to Solaris7 in HTML Format (Requires Account)");
        btnPostToS7.setFocusable(false);
        btnPostToS7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPostToS7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnPostToS7);
        tlbIconBar.add(jSeparator4);

        btnAddToForceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/clipboard--plus.png"))); // NOI18N
        btnAddToForceList.setToolTipText("Add This 'Mech to the Force List");
        btnAddToForceList.setFocusable(false);
        btnAddToForceList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddToForceList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnAddToForceList);

        btnForceList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/clipboard.png"))); // NOI18N
        btnForceList.setToolTipText("View Current Force List");
        btnForceList.setFocusable(false);
        btnForceList.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnForceList.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnForceList);
        tlbIconBar.add(jSeparator5);

        btnOptionsIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ssw/Images/gear.png"))); // NOI18N
        btnOptionsIcon.setToolTipText("View/Change User Preferences");
        btnOptionsIcon.setFocusable(false);
        btnOptionsIcon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOptionsIcon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tlbIconBar.add(btnOptionsIcon);
        tlbIconBar.add(jSeparator6);

        lblSelectVariant.setText("Selected Variant: ");
        lblSelectVariant.setEnabled(false);
        tlbIconBar.add(lblSelectVariant);

        cmbOmniVariant.setToolTipText("Change OmniMech Variant");
        cmbOmniVariant.setEnabled(false);
        cmbOmniVariant.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbOmniVariant.setPreferredSize(new java.awt.Dimension(150, 20));
        tlbIconBar.add(cmbOmniVariant);

        getContentPane().add(tlbIconBar);

        pnlBasicSetup.setLayout(new javax.swing.BoxLayout(pnlBasicSetup, javax.swing.BoxLayout.LINE_AXIS));

        pnlBasicSetupLeft.setLayout(new javax.swing.BoxLayout(pnlBasicSetupLeft, javax.swing.BoxLayout.PAGE_AXIS));

        pnlBasicInformation.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Basic Information"));
        pnlBasicInformation.setLayout(new javax.swing.BoxLayout(pnlBasicInformation, javax.swing.BoxLayout.PAGE_AXIS));

        pnlBasicInfo1.setLayout(new javax.swing.BoxLayout(pnlBasicInfo1, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo1.add( Box.createHorizontalGlue() );

        lblMechName.setText("Mech Name: ");
        pnlBasicInfo1.add(lblMechName);

        txtMechName.setMinimumSize(new java.awt.Dimension(150, 20));
        txtMechName.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo1.add(txtMechName);

        pnlBasicInformation.add(pnlBasicInfo1);

        pnlBasicInfo2.setLayout(new javax.swing.BoxLayout(pnlBasicInfo2, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo2.add( Box.createHorizontalGlue() );

        lblModel.setText("Model: ");
        pnlBasicInfo2.add(lblModel);

        txtMechModel.setMinimumSize(new java.awt.Dimension(150, 20));
        txtMechModel.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo2.add(txtMechModel);

        pnlBasicInformation.add(pnlBasicInfo2);

        pnlBasicInfo3.setLayout(new javax.swing.BoxLayout(pnlBasicInfo3, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo3.add( Box.createHorizontalGlue() );

        lblMechSource.setText("Source: ");
        pnlBasicInfo3.add(lblMechSource);

        txtSource.setMinimumSize(new java.awt.Dimension(150, 20));
        txtSource.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo3.add(txtSource);

        pnlBasicInformation.add(pnlBasicInfo3);

        pnlBasicInfo4.setLayout(new javax.swing.BoxLayout(pnlBasicInfo4, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo4.add( Box.createHorizontalGlue() );

        lblRulesLevel.setText("Rules Level: ");
        pnlBasicInfo4.add(lblRulesLevel);

        cmbRulesLevel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbRulesLevel.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbRulesLevel.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo4.add(cmbRulesLevel);

        pnlBasicInformation.add(pnlBasicInfo4);

        pnlBasicInfo5.setLayout(new javax.swing.BoxLayout(pnlBasicInfo5, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo5.add( Box.createHorizontalGlue() );

        lblMechEra.setText("Tech Era: ");
        pnlBasicInfo5.add(lblMechEra);

        cmbMechEra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMechEra.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbMechEra.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo5.add(cmbMechEra);

        pnlBasicInformation.add(pnlBasicInfo5);

        pnlBasicInfo6.setLayout(new javax.swing.BoxLayout(pnlBasicInfo6, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo6.add( Box.createHorizontalGlue() );

        lblTechBase.setText("Tech Base: ");
        pnlBasicInfo6.add(lblTechBase);

        cmbTechBase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTechBase.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbTechBase.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo6.add(cmbTechBase);

        pnlBasicInformation.add(pnlBasicInfo6);

        pnlBasicInfo7.setLayout(new javax.swing.BoxLayout(pnlBasicInfo7, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo7.add( Box.createHorizontalGlue() );

        lblEraYears.setText("2443~2800");
        pnlBasicInfo7.add(lblEraYears);

        pnlBasicInformation.add(pnlBasicInfo7);

        pnlBasicInfo8.setLayout(new javax.swing.BoxLayout(pnlBasicInfo8, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo8.add( Box.createHorizontalGlue() );

        lblProdYear.setText("Production Year: ");
        pnlBasicInfo8.add(lblProdYear);

        txtProdYear.setMinimumSize(new java.awt.Dimension(150, 20));
        txtProdYear.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo8.add(txtProdYear);

        pnlBasicInformation.add(pnlBasicInfo8);

        pnlBasicInfo9.setLayout(new javax.swing.BoxLayout(pnlBasicInfo9, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo9.add( Box.createHorizontalGlue() );

        chkYearRestrict.setText("Restrict Availability by Year");
        pnlBasicInfo9.add(chkYearRestrict);

        pnlBasicInformation.add(pnlBasicInfo9);

        pnlBasicInfo10.setLayout(new javax.swing.BoxLayout(pnlBasicInfo10, javax.swing.BoxLayout.LINE_AXIS));
        pnlBasicInfo10.add( Box.createHorizontalGlue() );

        jLabel9.setText("Fluff Era: ");
        pnlBasicInfo10.add(jLabel9);

        cmbFluffEra.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFluffEra.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbFluffEra.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlBasicInfo10.add(cmbFluffEra);

        pnlBasicInformation.add(pnlBasicInfo10);

        pnlBasicSetupLeft.add(pnlBasicInformation);

        pnlChassis.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Chassis"));
        pnlChassis.setLayout(new javax.swing.BoxLayout(pnlChassis, javax.swing.BoxLayout.PAGE_AXIS));

        pnlChassis1.setLayout(new javax.swing.BoxLayout(pnlChassis1, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis1.add( Box.createHorizontalGlue() );

        lblTonnage.setText("Tonnage: ");
        pnlChassis1.add(lblTonnage);

        cmbTonnage.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbTonnage.setMinimumSize(new java.awt.Dimension(60, 20));
        cmbTonnage.setPreferredSize(new java.awt.Dimension(60, 20));
        pnlChassis1.add(cmbTonnage);

        lblMechType.setText("Light Mech");
        pnlChassis1.add(lblMechType);

        pnlChassis.add(pnlChassis1);

        pnlChassis2.setLayout(new javax.swing.BoxLayout(pnlChassis2, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis2.add( Box.createHorizontalGlue() );

        lblUnitType.setText("Mech Type: ");
        pnlChassis2.add(lblUnitType);

        cmbMechType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMechType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbMechType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis2.add(cmbMechType);

        pnlChassis.add(pnlChassis2);

        pnlChassis3.setLayout(new javax.swing.BoxLayout(pnlChassis3, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis3.add( Box.createHorizontalGlue() );

        lblMotiveType.setText("Motive Type: ");
        pnlChassis3.add(lblMotiveType);

        cmbMotiveType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbMotiveType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbMotiveType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis3.add(cmbMotiveType);

        pnlChassis.add(pnlChassis3);

        pnlChassis4.setLayout(new javax.swing.BoxLayout(pnlChassis4, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis4.add( Box.createHorizontalGlue() );

        chkOmnimech.setText("OmniMech");
        pnlChassis4.add(chkOmnimech);

        pnlChassis.add(pnlChassis4);

        pnlChassis5.setLayout(new javax.swing.BoxLayout(pnlChassis5, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis5.add( Box.createHorizontalGlue() );

        lblInternalType.setText("Internal Structure: ");
        pnlChassis5.add(lblInternalType);

        cmbInternalType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbInternalType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbInternalType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis5.add(cmbInternalType);

        pnlChassis.add(pnlChassis5);

        pnlChassis6.setLayout(new javax.swing.BoxLayout(pnlChassis6, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis6.add( Box.createHorizontalGlue() );

        lblEngineType.setText("Engine Type: ");
        pnlChassis6.add(lblEngineType);

        cmbEngineType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbEngineType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbEngineType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis6.add(cmbEngineType);

        pnlChassis.add(pnlChassis6);

        pnlChassis7.setLayout(new javax.swing.BoxLayout(pnlChassis7, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis7.add( Box.createHorizontalGlue() );

        lblGyroType.setText("Gyro Type: ");
        pnlChassis7.add(lblGyroType);

        cmbGyroType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbGyroType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbGyroType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis7.add(cmbGyroType);

        pnlChassis.add(pnlChassis7);

        pnlChassis8.setLayout(new javax.swing.BoxLayout(pnlChassis8, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis8.add( Box.createHorizontalGlue() );

        lblCockpit.setText("Cockpit Type: ");
        pnlChassis8.add(lblCockpit);

        cmbCockpitType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCockpitType.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbCockpitType.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis8.add(cmbCockpitType);

        pnlChassis.add(pnlChassis8);

        pnlChassis9.setLayout(new javax.swing.BoxLayout(pnlChassis9, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis9.add( Box.createHorizontalGlue() );

        chkCommandConsole.setText("Use Command Console");
        pnlChassis9.add(chkCommandConsole);

        pnlChassis.add(pnlChassis9);

        pnlChassis10.setLayout(new javax.swing.BoxLayout(pnlChassis10, javax.swing.BoxLayout.LINE_AXIS));
        pnlChassis10.add( Box.createHorizontalGlue() );

        lblPhysEnhance.setText("Enhancements: ");
        pnlChassis10.add(lblPhysEnhance);

        cmbPhysEnhance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPhysEnhance.setMinimumSize(new java.awt.Dimension(150, 20));
        cmbPhysEnhance.setPreferredSize(new java.awt.Dimension(150, 20));
        pnlChassis10.add(cmbPhysEnhance);

        pnlChassis.add(pnlChassis10);

        pnlBasicSetupLeft.add(pnlChassis);

        pnlBasicSetup.add(pnlBasicSetupLeft);

        pnlBasicSetupCenter.setLayout(new javax.swing.BoxLayout(pnlBasicSetupCenter, javax.swing.BoxLayout.PAGE_AXIS));
        pnlBasicSetup.add(pnlBasicSetupCenter);

        pnlBasicSetupRight.setLayout(new javax.swing.BoxLayout(pnlBasicSetupRight, javax.swing.BoxLayout.PAGE_AXIS));
        pnlBasicSetup.add(pnlBasicSetupRight);

        tbpMainTabPane.addTab("Basic Setup", pnlBasicSetup);

        javax.swing.GroupLayout pnlArmorLayout = new javax.swing.GroupLayout(pnlArmor);
        pnlArmor.setLayout(pnlArmorLayout);
        pnlArmorLayout.setHorizontalGroup(
            pnlArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlArmorLayout.setVerticalGroup(
            pnlArmorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("Armor", pnlArmor);

        javax.swing.GroupLayout pnlEquipmentLayout = new javax.swing.GroupLayout(pnlEquipment);
        pnlEquipment.setLayout(pnlEquipmentLayout);
        pnlEquipmentLayout.setHorizontalGroup(
            pnlEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlEquipmentLayout.setVerticalGroup(
            pnlEquipmentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("Equipment", pnlEquipment);

        javax.swing.GroupLayout pnlCriticalsLayout = new javax.swing.GroupLayout(pnlCriticals);
        pnlCriticals.setLayout(pnlCriticalsLayout);
        pnlCriticalsLayout.setHorizontalGroup(
            pnlCriticalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlCriticalsLayout.setVerticalGroup(
            pnlCriticalsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("Criticals", pnlCriticals);

        javax.swing.GroupLayout pnlFluffLayout = new javax.swing.GroupLayout(pnlFluff);
        pnlFluff.setLayout(pnlFluffLayout);
        pnlFluffLayout.setHorizontalGroup(
            pnlFluffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlFluffLayout.setVerticalGroup(
            pnlFluffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("Fluff", pnlFluff);

        javax.swing.GroupLayout pnlChartsLayout = new javax.swing.GroupLayout(pnlCharts);
        pnlCharts.setLayout(pnlChartsLayout);
        pnlChartsLayout.setHorizontalGroup(
            pnlChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlChartsLayout.setVerticalGroup(
            pnlChartsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("Charts", pnlCharts);

        javax.swing.GroupLayout pnlBattleforceLayout = new javax.swing.GroupLayout(pnlBattleforce);
        pnlBattleforce.setLayout(pnlBattleforceLayout);
        pnlBattleforceLayout.setHorizontalGroup(
            pnlBattleforceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        pnlBattleforceLayout.setVerticalGroup(
            pnlBattleforceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 489, Short.MAX_VALUE)
        );

        tbpMainTabPane.addTab("BattleForce", pnlBattleforce);

        getContentPane().add(tbpMainTabPane);

        pnlInfoPanel.setLayout(new javax.swing.BoxLayout(pnlInfoPanel, javax.swing.BoxLayout.LINE_AXIS));

        txtInfoTonnage.setEditable(false);
        txtInfoTonnage.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoTonnage.setText("Tonnage");
        txtInfoTonnage.setToolTipText("'Mech Tonnage");
        txtInfoTonnage.setMinimumSize(new java.awt.Dimension(72, 20));
        txtInfoTonnage.setPreferredSize(new java.awt.Dimension(72, 20));
        pnlInfoPanel.add(txtInfoTonnage);

        txtInfoFreeTons.setEditable(false);
        txtInfoFreeTons.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoFreeTons.setText("free tonnage");
        txtInfoFreeTons.setToolTipText("Free Tonnage in 'Mech");
        txtInfoFreeTons.setMinimumSize(new java.awt.Dimension(96, 20));
        txtInfoFreeTons.setPreferredSize(new java.awt.Dimension(96, 20));
        pnlInfoPanel.add(txtInfoFreeTons);

        txtInfoMaxHeat.setEditable(false);
        txtInfoMaxHeat.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoMaxHeat.setText("max heat");
        txtInfoMaxHeat.setToolTipText("Maximum Generated Heat (Change Amount Displayed in Preferences)");
        txtInfoMaxHeat.setMinimumSize(new java.awt.Dimension(77, 20));
        txtInfoMaxHeat.setPreferredSize(new java.awt.Dimension(77, 20));
        pnlInfoPanel.add(txtInfoMaxHeat);

        txtInfoHeatDiss.setEditable(false);
        txtInfoHeatDiss.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoHeatDiss.setText("heat dissipation");
        txtInfoHeatDiss.setToolTipText("Maximum Heat Dissipated Per Game Turn");
        txtInfoHeatDiss.setMinimumSize(new java.awt.Dimension(118, 20));
        txtInfoHeatDiss.setPreferredSize(new java.awt.Dimension(118, 20));
        pnlInfoPanel.add(txtInfoHeatDiss);

        jTextField4.setEditable(false);
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("free crits");
        jTextField4.setToolTipText("Free Critical Slots Available");
        jTextField4.setMinimumSize(new java.awt.Dimension(77, 20));
        jTextField4.setPreferredSize(new java.awt.Dimension(77, 20));
        pnlInfoPanel.add(jTextField4);

        txtInfoUnplaced.setEditable(false);
        txtInfoUnplaced.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoUnplaced.setText("unplaced crits");
        txtInfoUnplaced.setToolTipText("Unplaced Critical Slot Items");
        txtInfoUnplaced.setMinimumSize(new java.awt.Dimension(110, 20));
        txtInfoUnplaced.setPreferredSize(new java.awt.Dimension(110, 20));
        pnlInfoPanel.add(txtInfoUnplaced);

        txtInfoBattleValue.setEditable(false);
        txtInfoBattleValue.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoBattleValue.setText("bv");
        txtInfoBattleValue.setToolTipText("Battle Value of 'Mech");
        txtInfoBattleValue.setMinimumSize(new java.awt.Dimension(62, 20));
        txtInfoBattleValue.setPreferredSize(new java.awt.Dimension(62, 20));
        pnlInfoPanel.add(txtInfoBattleValue);

        txtInfoCost.setEditable(false);
        txtInfoCost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtInfoCost.setText("cost");
        txtInfoCost.setToolTipText("Cost (in C-Bills) of 'Mech");
        txtInfoCost.setMinimumSize(new java.awt.Dimension(125, 20));
        txtInfoCost.setPreferredSize(new java.awt.Dimension(125, 20));
        pnlInfoPanel.add(txtInfoCost);

        getContentPane().add(pnlInfoPanel);

        mnuFile.setText("File");

        mnuNewMech.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        mnuNewMech.setText("New Mech");
        mnuNewMech.setToolTipText("Create New 'Mech");
        mnuFile.add(mnuNewMech);

        mnuLoad.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_MASK));
        mnuLoad.setText("Load Mech");
        mnuLoad.setToolTipText("Load 'Mech from File");
        mnuFile.add(mnuLoad);

        mnuOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        mnuOpen.setText("Open");
        mnuOpen.setToolTipText("Show Open Dialogue");
        mnuFile.add(mnuOpen);

        mnuImport.setText("Import Mech...");

        mnuImportHMP.setText("from Heavy Metal Pro (HMP)");
        mnuImportHMP.setToolTipText("");
        mnuImport.add(mnuImportHMP);

        mnuBatchHMP.setText("Batch Import HMP Files");
        mnuImport.add(mnuBatchHMP);

        mnuFile.add(mnuImport);
        mnuFile.add(jSeparator7);

        mnuSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnuSave.setText("Save Mech");
        mnuFile.add(mnuSave);

        mnuSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuSaveAs.setText("Save Mech As");
        mnuFile.add(mnuSaveAs);

        mnuExport.setText("Export Mech...");

        mnuExportHTML.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        mnuExportHTML.setText("to HTML (Web)");
        mnuExport.add(mnuExportHTML);

        mnuExportMTF.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        mnuExportMTF.setText("to MTF (MegaMek)");
        mnuExport.add(mnuExportMTF);

        mnuExportTXT.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        mnuExportTXT.setText("to TXT (Text)");
        mnuExport.add(mnuExportTXT);

        mnuExportClipboard.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuExportClipboard.setText("to Clipboard (Text)");
        mnuExport.add(mnuExportClipboard);

        mnuCreateTCGMech.setText("to TCG Format (Card, Incomplete)");
        mnuExport.add(mnuCreateTCGMech);

        mnuFile.add(mnuExport);
        mnuFile.add(jSeparator8);

        mnuPrint.setText("Print");

        mnuPrintCurrentMech.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnuPrintCurrentMech.setText("Current Mech");
        mnuPrint.add(mnuPrintCurrentMech);

        mnuPrintSavedMech.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPrintSavedMech.setText("Saved Mech");
        mnuPrint.add(mnuPrintSavedMech);

        mnuPrintBatch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPrintBatch.setText("Batch Print Mechs");
        mnuPrint.add(mnuPrintBatch);

        mnuFile.add(mnuPrint);

        mnuPrintPreview.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnuPrintPreview.setText("Print Preview");
        mnuFile.add(mnuPrintPreview);

        mnuPostS7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        mnuPostS7.setText("Post Mech to Solaris7.com");
        mnuFile.add(mnuPostS7);
        mnuFile.add(jSeparator9);

        mnuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        mnuExit.setText("Exit");
        mnuFile.add(mnuExit);

        mnuMainMenu.add(mnuFile);

        mnuTools.setText("Tools");

        mnuSummary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        mnuSummary.setText("Show Summary");
        mnuTools.add(mnuSummary);

        mnuCostBVBreakdown.setText("Cost/BV Breakdown");
        mnuTools.add(mnuCostBVBreakdown);

        mnuTextTRO.setText("Show Text/TRO Format");
        mnuTools.add(mnuTextTRO);

        mnuUnlock.setText("Unlock Chassis");
        mnuUnlock.setEnabled(false);
        mnuTools.add(mnuUnlock);
        mnuTools.add(jSeparator10);

        mnuOptions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnuOptions.setText("Preferences");
        mnuTools.add(mnuOptions);

        mnuViewToolbar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.ALT_MASK));
        mnuViewToolbar.setSelected(true);
        mnuViewToolbar.setText("View Toolbar");
        mnuTools.add(mnuViewToolbar);

        mnuClearUserData.setText("Clear User Data");
        mnuTools.add(mnuClearUserData);

        mnuMainMenu.add(mnuTools);

        mnuHelp.setText("Help");

        mnuCredits.setText("Credits");
        mnuHelp.add(mnuCredits);

        mnuAboutSSW.setText("About Solaris Skunk Werks");
        mnuHelp.add(mnuAboutSSW);

        mnuMainMenu.add(mnuHelp);

        setJMenuBar(mnuMainMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToForceList;
    private javax.swing.JButton btnChatInfo;
    private javax.swing.JButton btnExportClipboardIcon;
    private javax.swing.JButton btnExportHTMLIcon;
    private javax.swing.JButton btnExportMTFIcon;
    private javax.swing.JButton btnExportTextIcon;
    private javax.swing.JButton btnForceList;
    private javax.swing.JButton btnNewIcon;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnOptionsIcon;
    private javax.swing.JButton btnPostToS7;
    private javax.swing.JButton btnPrintIcon;
    private javax.swing.JButton btnPrintPreview;
    private javax.swing.JButton btnSaveIcon;
    private javax.swing.JCheckBox chkCommandConsole;
    private javax.swing.JCheckBox chkOmnimech;
    private javax.swing.JCheckBox chkYearRestrict;
    private javax.swing.JComboBox cmbCockpitType;
    private javax.swing.JComboBox cmbEngineType;
    private javax.swing.JComboBox cmbFluffEra;
    private javax.swing.JComboBox cmbGyroType;
    private javax.swing.JComboBox cmbInternalType;
    private javax.swing.JComboBox cmbMechEra;
    private javax.swing.JComboBox cmbMechType;
    private javax.swing.JComboBox cmbMotiveType;
    private javax.swing.JComboBox cmbOmniVariant;
    private javax.swing.JComboBox cmbPhysEnhance;
    private javax.swing.JComboBox cmbRulesLevel;
    private javax.swing.JComboBox cmbTechBase;
    private javax.swing.JComboBox cmbTonnage;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar.Separator jSeparator5;
    private javax.swing.JToolBar.Separator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblCockpit;
    private javax.swing.JLabel lblEngineType;
    private javax.swing.JLabel lblEraYears;
    private javax.swing.JLabel lblGyroType;
    private javax.swing.JLabel lblInternalType;
    private javax.swing.JLabel lblMechEra;
    private javax.swing.JLabel lblMechName;
    private javax.swing.JLabel lblMechSource;
    private javax.swing.JLabel lblMechType;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblMotiveType;
    private javax.swing.JLabel lblPhysEnhance;
    private javax.swing.JLabel lblProdYear;
    private javax.swing.JLabel lblRulesLevel;
    private javax.swing.JLabel lblSelectVariant;
    private javax.swing.JLabel lblTechBase;
    private javax.swing.JLabel lblTonnage;
    private javax.swing.JLabel lblUnitType;
    private javax.swing.JMenuItem mnuAboutSSW;
    private javax.swing.JMenuItem mnuBatchHMP;
    private javax.swing.JMenuItem mnuClearUserData;
    private javax.swing.JMenuItem mnuCostBVBreakdown;
    private javax.swing.JMenuItem mnuCreateTCGMech;
    private javax.swing.JMenuItem mnuCredits;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenu mnuExport;
    private javax.swing.JMenuItem mnuExportClipboard;
    private javax.swing.JMenuItem mnuExportHTML;
    private javax.swing.JMenuItem mnuExportMTF;
    private javax.swing.JMenuItem mnuExportTXT;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuImport;
    private javax.swing.JMenuItem mnuImportHMP;
    private javax.swing.JMenuItem mnuLoad;
    private javax.swing.JMenuBar mnuMainMenu;
    private javax.swing.JMenuItem mnuNewMech;
    private javax.swing.JMenuItem mnuOpen;
    private javax.swing.JMenuItem mnuOptions;
    private javax.swing.JMenuItem mnuPostS7;
    private javax.swing.JMenu mnuPrint;
    private javax.swing.JMenuItem mnuPrintBatch;
    private javax.swing.JMenuItem mnuPrintCurrentMech;
    private javax.swing.JMenuItem mnuPrintPreview;
    private javax.swing.JMenuItem mnuPrintSavedMech;
    private javax.swing.JMenuItem mnuSave;
    private javax.swing.JMenuItem mnuSaveAs;
    private javax.swing.JMenuItem mnuSummary;
    private javax.swing.JMenuItem mnuTextTRO;
    private javax.swing.JMenu mnuTools;
    private javax.swing.JMenuItem mnuUnlock;
    private javax.swing.JCheckBoxMenuItem mnuViewToolbar;
    private javax.swing.JPanel pnlArmor;
    private javax.swing.JPanel pnlBasicInfo1;
    private javax.swing.JPanel pnlBasicInfo10;
    private javax.swing.JPanel pnlBasicInfo2;
    private javax.swing.JPanel pnlBasicInfo3;
    private javax.swing.JPanel pnlBasicInfo4;
    private javax.swing.JPanel pnlBasicInfo5;
    private javax.swing.JPanel pnlBasicInfo6;
    private javax.swing.JPanel pnlBasicInfo7;
    private javax.swing.JPanel pnlBasicInfo8;
    private javax.swing.JPanel pnlBasicInfo9;
    private javax.swing.JPanel pnlBasicInformation;
    private javax.swing.JPanel pnlBasicSetup;
    private javax.swing.JPanel pnlBasicSetupCenter;
    private javax.swing.JPanel pnlBasicSetupLeft;
    private javax.swing.JPanel pnlBasicSetupRight;
    private javax.swing.JPanel pnlBattleforce;
    private javax.swing.JPanel pnlCharts;
    private javax.swing.JPanel pnlChassis;
    private javax.swing.JPanel pnlChassis1;
    private javax.swing.JPanel pnlChassis10;
    private javax.swing.JPanel pnlChassis2;
    private javax.swing.JPanel pnlChassis3;
    private javax.swing.JPanel pnlChassis4;
    private javax.swing.JPanel pnlChassis5;
    private javax.swing.JPanel pnlChassis6;
    private javax.swing.JPanel pnlChassis7;
    private javax.swing.JPanel pnlChassis8;
    private javax.swing.JPanel pnlChassis9;
    private javax.swing.JPanel pnlCriticals;
    private javax.swing.JPanel pnlEquipment;
    private javax.swing.JPanel pnlFluff;
    private javax.swing.JPanel pnlInfoPanel;
    private javax.swing.JTabbedPane tbpMainTabPane;
    private javax.swing.JToolBar tlbIconBar;
    private javax.swing.JTextField txtInfoBattleValue;
    private javax.swing.JTextField txtInfoCost;
    private javax.swing.JTextField txtInfoFreeTons;
    private javax.swing.JTextField txtInfoHeatDiss;
    private javax.swing.JTextField txtInfoMaxHeat;
    private javax.swing.JTextField txtInfoTonnage;
    private javax.swing.JTextField txtInfoUnplaced;
    private javax.swing.JTextField txtMechModel;
    private javax.swing.JTextField txtMechName;
    private javax.swing.JTextField txtProdYear;
    private javax.swing.JTextField txtSource;
    // End of variables declaration//GEN-END:variables
}
