

package BFB.GUI;

import Force.*;
import battleforce.BattleForce;
import filehandlers.Media;
import java.io.File;
import java.io.IOException;
import javax.swing.DefaultListModel;

public class dlgGroup extends javax.swing.JDialog {
    private Scenario scenario;
    private Media media = new Media();
    private Group curGroup;
    private frmBase parent;

    public dlgGroup(java.awt.Frame parent, boolean modal, Scenario scenario) {
        super(parent, modal);
        initComponents();

        this.parent = (frmBase) parent;
        this.scenario = scenario;

        loadGroupList();
        lstGroups.setSelectedIndex(0);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpType = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstGroups = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblGroupLogo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstUnits = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblBV = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblPV = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        rdoInnerSphere = new javax.swing.JRadioButton();
        rdoClan = new javax.swing.JRadioButton();
        rdoComstar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnCancel.setText("Close");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(536, Short.MAX_VALUE)
                .addComponent(btnCancel))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCancel)
        );

        lstGroups.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstGroups.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstGroupsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstGroups);

        jLabel1.setText("Groups");

        lblGroupLogo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblGroupLogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGroupLogoMouseClicked(evt);
            }
        });

        lstUnits.setBackground(new java.awt.Color(240, 240, 240));
        lstUnits.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstUnits);

        jLabel3.setText("Group Logo");

        jLabel4.setText("Units");

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel5.setText("Total BV:");

        lblBV.setFont(new java.awt.Font("Arial", 1, 12));
        lblBV.setText("0");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Total PV:");

        lblPV.setFont(new java.awt.Font("Arial", 1, 12));
        lblPV.setText("0");

        jLabel2.setText("Group Name");

        txtGroupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGroupNameActionPerformed(evt);
            }
        });

        jLabel6.setText("Group Type");

        btnGrpType.add(rdoInnerSphere);
        rdoInnerSphere.setText("Inner Sphere (4)");
        rdoInnerSphere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoInnerSphereActionPerformed(evt);
            }
        });

        btnGrpType.add(rdoClan);
        rdoClan.setText("Clan (5)");
        rdoClan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoClanActionPerformed(evt);
            }
        });

        btnGrpType.add(rdoComstar);
        rdoComstar.setText("Comstar/Word of Blake (6)");
        rdoComstar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoComstarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblGroupLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdoInnerSphere)
                                    .addComponent(rdoClan)
                                    .addComponent(rdoComstar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblBV))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtGroupName, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                                    .addComponent(jLabel6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPV)
                        .addGap(49, 49, 49)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtGroupName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoInnerSphere)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoClan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdoComstar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblPV)
                            .addComponent(jLabel5)
                            .addComponent(lblBV)))
                    .addComponent(lblGroupLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadGroupList() {
        DefaultListModel gModel = new DefaultListModel();
        for ( Force f : scenario.getForces() ) {
            for ( Group g : f.Groups ) {
                gModel.addElement(g);
            }
        }
        lstGroups.setModel(gModel);
    }

    private void lstGroupsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstGroupsValueChanged
        if ( lstGroups.getSelectedValue() != null ) {
            for ( Force f : scenario.getForces() ) {
                for ( Group g : f.Groups ) {
                    if ( g.equals(lstGroups.getSelectedValue()) ) {
                        curGroup = g;
                    }
                }
            }
            lblGroupLogo.setIcon(null);
            if ( !curGroup.getLogo().isEmpty() ) media.setLogo(lblGroupLogo, new File(curGroup.getLogo()));
            txtGroupName.setText(curGroup.getName());
            if ( curGroup.getType().equals(BattleForce.InnerSphere) )
                rdoInnerSphere.setSelected(true);
            else if ( curGroup.getType().equals(BattleForce.Clan) )
                rdoClan.setSelected(true);
            else
                rdoComstar.setSelected(true);
            lblBV.setText(curGroup.getTotalBV()+"");
            lblPV.setText(curGroup.getTotalPV()+"");
            media.setLogo(lblGroupLogo, new File(curGroup.getLogo()));

            DefaultListModel uModel = new DefaultListModel();
            for ( Unit u : curGroup.getUnits() ) {
                uModel.addElement(u);
            }
            lstUnits.setModel(uModel);
        }
    }//GEN-LAST:event_lstGroupsValueChanged

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_btnCancelActionPerformed

    private void lblGroupLogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGroupLogoMouseClicked
        File Logo = media.SelectImage(parent.Prefs.get("LastOpenLogo", ""), "Select Logo");
        try {
            lblGroupLogo.setIcon(null);
            curGroup.setLogo(Logo.getCanonicalPath());
            media.setLogo(lblGroupLogo, Logo);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
}//GEN-LAST:event_lblGroupLogoMouseClicked

    private void txtGroupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGroupNameActionPerformed
        curGroup.setName(txtGroupName.getText());
        loadGroupList();
    }//GEN-LAST:event_txtGroupNameActionPerformed

    private void rdoInnerSphereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoInnerSphereActionPerformed
        curGroup.setType(BattleForce.InnerSphere);
        loadGroupList();
    }//GEN-LAST:event_rdoInnerSphereActionPerformed

    private void rdoClanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoClanActionPerformed
        curGroup.setType(BattleForce.Clan);
        loadGroupList();
    }//GEN-LAST:event_rdoClanActionPerformed

    private void rdoComstarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoComstarActionPerformed
        curGroup.setType(BattleForce.Comstar);
        loadGroupList();
    }//GEN-LAST:event_rdoComstarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup btnGrpType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBV;
    private javax.swing.JLabel lblGroupLogo;
    private javax.swing.JLabel lblPV;
    private javax.swing.JList lstGroups;
    private javax.swing.JList lstUnits;
    private javax.swing.JRadioButton rdoClan;
    private javax.swing.JRadioButton rdoComstar;
    private javax.swing.JRadioButton rdoInnerSphere;
    private javax.swing.JTextField txtGroupName;
    // End of variables declaration//GEN-END:variables

}
