#
# SSW CI
#
name: Java CI with Gradle

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    #
    # Perform a Release Build
    #
    - name: Build with Gradle
      run: ./gradlew releaseBuild

    #
    # Resolve version name for release archive
    #
    - name: Generate name for archive
      run: echo "SSW_VERSION=$(ls ./build/release)-$(git rev-parse --short=10 HEAD)" >> $GITHUB_ENV

    #
    # Upload release distribution zipfile
    #
    - name: Upload Releases
      uses: actions/upload-artifact@v2-preview

      with:
        path: ./build/release/
        name: ${{ env.SSW_VERSION }}
